config/routes.rb
Rails.application.routes.draw do
 
  resources :session, only: [:create]
  resources :places
  resources :users
  resources :admin, only: [:index]

  root 'welcome#index'
  post "/bookmarks" => "places#bookmark", as: "bookmark_create"
  post "/reviews" => "places#review", as: "review_create"

  get "/sign_in" => "session#new", as: "sign_in"
  delete "/sign_out" => "session#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  get "/search" => "places#search", as: "search"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :reviews
	has_many :bookmarks

	mount_uploader :image, ImageUploader

	geocoded_by :address
	after_validation :geocode, :if => :address_changed?

	def self.search(search)
	  where("name ilike ? OR description ilike ?", "%#{search}%", "%#{search}%")
	end
	
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :reviews
	has_many :bookmarks

	mount_uploader :profile_pic, ProfilePicUploader

	validates_uniqueness_of :email, :username


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :check_user
	before_action :check_admin
	def index
		@places = Place.all.paginate(:page => params[:page], :per_page =>2)
	end

	def show
		
	end

	def check_user
		if !current_user
		redirect_to root_path, notice: "No trespassing. "
		end
	end

	def check_admin
		if !current_user.admin
		redirect_to root_path, notice: "No trespassing."
		end
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :check_user
	before_action :check_admin

	def index
		@places = Place.all.paginate(:page => params[:page], :per_page =>2)
	end

	def show
		@place = Place.find(params[:id])
		@review = Review.new
		@show_review = Review.where(place_id: @place.id)
	end

	def new
		@place = Place.new
	end

	def create
		@place = Place.new(new_params)
		if @place.save
		    redirect_to places_path
		else
		    render "new"
		end
	end

	def destroy
		@place = Place.find(params[place.id])
		@place.destroy	
		redirect_to admin_index_path
	end

	def bookmark		

	 	@place = Place.find(params[:place_id])
	 	if Bookmark.where(place_id: @place.id, user_id: current_user.id).exists?
	 	else
	 		@bookmarked = Bookmark.new(place_id: @place.id, user_id: current_user.id)
	 		if @bookmarked.save
				redirect_to user_path(current_user.id)
			else
				redirect_to root_path
			end
		end
	end

	def review

	 	@user = current_user
	 	@place = Place.find(params[:place_id])
	 	@review = Review.new(review_params)
	 	@review.user_id = current_user.id
	 	@review.place_id =@place.id
	 		if @review.save
				redirect_to user_path(current_user.id)
			else
				redirect_to root_path
			end
	end

	def search
		@places = Place.all
		if params[:search]
		  @places = Place.search(params[:search]).order("created_at DESC")
		else
		@places = Place.all.order("created_at DESC")
		end	
	end

	private 

	def new_params
		params.require(:place).permit(:name, :description, :image, :address, :latitude, :longtitude)
	end

	def review_params
		params.require(:review).permit(:place_id, :user_id, :description)
	end

	def check_user
		if !current_user
			flash[:notice] = "Sorry, please sign in to continue!"
			redirect_to sign_in_path
		end 
	end

	def check_admin
		if current_user.admin
			redirect_to admin_index_path
		end
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
      if !user.admin
  		redirect_to root_path, flash: {notice: "Signed in"}
      else
      redirect_to admin_index_path
      end
  	else
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path, flash: {notice: "Signed out"}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(allowed_params)
		if @user.save
		    session[:user_id] = @user.id
		    redirect_to root_path
		else
		    render "new"
		end
	end

	def edit
		@user = current_user
	end

	def update
		current_user.update(allowed_params)
		current_user.save
		redirect_to user_path(current_user.id)
	end

	private

	def allowed_params
		params.require(:user).permit(:username, :email, :password, :profile_pic)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@place = Place.last
  	@review = @place.reviews
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<%= will_paginate @places %>  
 
<% @places.each do |place| %>
<div class="card" style="width: 18rem;">
  <%= image_tag place.image_url.to_s %></br>
  <div class="card-body">
    <h5 class="card-title"><%= link_to place.name, place_path(place) %></h5>
    <p class="card-text"><%= place.description %></p>
    <%= button_to "Delete", place_path(place.id), method: :delete %>
  </div>
</div></br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
  <% end %>

 <%= form_tag(search_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search" %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>

  <div>
  <% if current_user %>
  Logged in as <%= current_user.email %>
  <%= button_to "Home", root_path, method: :get %>
  <%= button_to "Attractions", places_path, method: :get %>
  <%= button_to "Profile page", user_path(current_user.id), method: :get %>
  <%= button_to "Sign out", sign_out_path, method: :delete %>
  <% else %>  
  <%= button_to "Sign in", sign_in_path, method: :get %>
  <%= button_to "Sign up", sign_up_path, method: :get %>
  <% end %>
  </div>
    <%= yield %>
  </body>
</html>